### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'start_idx'

### ISSUE THREAD

**Issue by ccllyyhhhh** [DMU-XMU/SAR#1]
when ./run.sh --agent curl --auxiliary sar --env carla.highway.map04
TypeError: __init__() got an unexpected keyword argument 'start_idx'

**Comment by DMU-XMU** [comment]
Hello, I forgot to prompt the user to modify the distracting_control package file. In distracting_control/background.py, we need to add a start_idx=None variable to the def __init__ function of the class DistractingBackgroundEnv(control.Environment, GetStateMixin), then with the following code:
# Optionally use only the first num_paths many paths.
            if num_videos is not None:
                if num_videos > len(video_paths) or num_videos < 0:
                    raise ValueError(f'`num_bakground_paths` is {num_videos} but '
                                     'should not be larger than the number of available '
                                     f'background paths ({len(video_paths)}) and at '
                                     'least 0.')
                if start_idx is None:
                    video_paths = video_paths[:num_videos]
                else:
                    video_paths = video_paths[start_idx:start_idx+num_videos]
